### General
image: docker:latest

# Scripts
install:
    - echo "Install docker compose ..."
    - apk add --update python py-pip python-dev && pip install docker-compose
    - echo "Docker info & version:"
    - docker -D info
    - docker version
    - echo "Docker compose info:"
    - docker-compose version

script:
    - echo "Testing ..."
    - php vendor/bin/simple-phpunit
    - echo "Deploying ..."
    - php vendor/bin/dep deploy qa -vvv
