image: docker:latest

services:
    - docker:dind

before_script:
    - apk add --update python py-pip python-dev && pip install docker-compose
    - docker version
    - docker-compose version

stages:
    - build
    - test

build:
    stage: build
    script:
        - docker-compose build
test:
    stage: test
    script:
        - php vendor/bin/simple-phpunit
