### General
image: docker:latest

variables:
    DOCKER_DRIVER: overlay2

services:
    - docker:dind

stages:
    - build
    - test
    - deploy

# Scripts
before_script:
    - apk add --update python py-pip python-dev && pip install docker-compose
    - docker -D info
    - docker version
    - docker-compose version

### Build
build:
    stage: build
    script:
        - echo "Building the app ..."
        - docker-compose build

### Test
test:
    stage: test
    script:
        - echo "Testing the app ..."
        - php vendor/bin/simple-phpunit

### Deploy
deploy_qa:
    stage: deploy
    environment:
        name: qa
        url: http://symfony-boilerplate.lt1.corcosoft.com
    only:
        - develop
    script:
        - echo "Deploying the app to *qa* ..."
        - dep deploy qa -vvv

deploy_stag:
    stage: deploy
    environment:
        name: stag
        url: http://stag.example.com
    only:
        - master
    script:
        - echo "Deploying the app to *stag* ..."
        - dep deploy stag -vvv

deploy_prod:
    stage: deploy
    environment:
        name: prod
        url: http://example.com
    only:
        - master
    script:
        - echo "Deploying the app to *prod* ..."
        - dep deploy prod -vvv
    when: manual
