image: docker:latest

services:
    - docker:dind

before_script:
    - apk add --update python py-pip python-dev && pip install docker-compose
    - docker version
    - docker-compose version

test:docker:
    script:
        - docker-compose build
        - php vendor/bin/simple-phpunit
