image: tmaier/docker-compose:latest

services:
    - docker:dind

before_script:
    - docker-compose build

test:docker:
    script:
        - docker-compose build
        - php vendor/bin/simple-phpunit
