### General
image: docker:latest

variables:
    DOCKER_DRIVER: overlay2
    CI_REGISTRY_IMAGE_FULL: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

services:
    - docker:dind

stages:
    - build
    - test
    - deploy

# Scripts
before_script:
    - echo "Install docker compose ..."
    - apk add --update python py-pip python-dev && pip install docker-compose
    - echo "Docker info & version:"
    - docker -D info
    - docker version
    - echo "Docker compose info:"
    - docker-compose version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

### Build
build:
    stage: build
    script:
        - echo "Building the app ..."
        - docker build --pull -t $CI_REGISTRY_IMAGE_FULL .
        - docker push $CI_REGISTRY_IMAGE_FULL

### Test
test:
    stage: test
    script:
        - echo "Testing the app ..."
        - docker pull $CI_REGISTRY_IMAGE_FULL
        - docker run $CI_REGISTRY_IMAGE_FULL php vendor/bin/simple-phpunit

### Deploy
deploy_qa:
    stage: deploy
    environment:
        name: qa
        url: http://symfony-boilerplate.lt1.corcosoft.com
    only:
        - develop
    script:
        - echo "Deploying the app to *qa* ..."
        - docker pull $CI_REGISTRY_IMAGE_FULL
        - docker run $CI_REGISTRY_IMAGE_FULL php vendor/bin/dep deploy qa -vvv

deploy_stag:
    stage: deploy
    environment:
        name: stag
        url: http://stag.example.com
    only:
        - master
    script:
        - echo "Deploying the app to *stag* ..."
        - docker pull $CI_REGISTRY_IMAGE_FULL
        - docker run $CI_REGISTRY_IMAGE_FULL php vendor/bin/dep deploy stag -vvv

deploy_prod:
    stage: deploy
    environment:
        name: prod
        url: http://example.com
    only:
        - master
    script:
        - echo "Deploying the app to *prod* ..."
        - docker pull $CI_REGISTRY_IMAGE_FULL
        - docker run $CI_REGISTRY_IMAGE_FULL php vendor/bin/dep deploy prod -vvv
    when: manual
