version: '3'

networks:

    default:
        driver: bridge

services:

    web:
        build: .
        links:
            - mysql
            - redis
            - memcached
        depends_on:
            - mysql
            - redis
            - memcached
        volumes:
            - .:/var/www/html
        networks:
            - default

    mysql:
        image: mysql
        volumes:
            - "./docker/var/logs/mysql:/var/log/mysql"
            - "./docker/var/data/mysql:/var/lib/mysql"
        networks:
            - default
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sfbp
            MYSQL_USER: sfbp
            MYSQL_PASSWORD: sfbp

    redis:
        image: redis
        networks:
            - default

    memcached:
        image: memcached
        networks:
            - default
