version: '3'

services:

  app:
    build: .
    dockerfile: Dockerfile
    links:
      - redis
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html

  redis:
    image: redis:latest
    
  memcached:
    image: memcached:latest
