# TODO: not working... some issue with networking... needs fixing
version: "3"

# Services
services:
    web:
        build: .
        links:
            - mysql
            - redis
            - memcached
        depends_on:
            - mysql
            - redis
            - memcached
        volumes:
            - ".:${PROJECT_DIR}"
        ports:
            - ${LOCAL_WEB_HTTP_PORT}:80
            - ${LOCAL_WEB_HTTPS_PORT}:443
        networks:
            backend:
                ipv4_address: 10.10.16.16

    mysql:
        image: mysql
        user: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - "./docker/var/logs/mysql:/var/log/mysql"
            - "./docker/var/data/mysql:/var/lib/mysql"
        ports:
            - ${LOCAL_MYSQL_PORT}:3306
        networks:
            backend:
                ipv4_address: 10.10.16.16

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - ${LOCAL_PHPMYADMIN_PORT}:80
        networks:
            backend:
                ipv4_address: 10.10.16.16

    redis:
        image: redis
        ports:
            - ${LOCAL_REDIS_PORT}:6379
        networks:
            backend:
                ipv4_address: 10.10.16.16

    memcached:
        image: memcached
        ports:
            - ${LOCAL_MEMCACHED_PORT}:11211
        networks:
            backend:
                ipv4_address: 10.10.16.16

# Networks
networks:
    backend:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.10.16.0/24
