version: "3"

networks:

    default:
        driver: bridge

services:

    web:
        build: .
        links:
            - mysql
            - redis
            - memcached
        depends_on:
            - mysql
            - redis
            - memcached
        ports:
            - "81:80"
            - "444:443"
        volumes:
            - "./:/var/www/html/"
        networks:
            - default

    mysql:
        image: mysql
        user: mysql
        ports:
            - "3307:3306"
        volumes:
            - "./docker/var/logs/mysql/:/var/log/mysql/"
            - "./docker/var/data/mysql/:/var/lib/mysql/"
        networks:
            - default
        environment:
            MYSQL_ROOT_PASSWORD: sfbp
            MYSQL_DATABASE: sfbp
            MYSQL_USER: sfbp
            MYSQL_PASSWORD: sfbp

    redis:
        image: redis
        ports:
            - "6380:6379"
        networks:
            - default

    memcached:
        image: memcached
        ports:
            - "11212:11211"
        networks:
            - default
