version: "3"

# Services
services:
    web:
        build: .
        links:
            - mysql
            - redis
            - memcached
        depends_on:
            - mysql
            - redis
            - memcached
        volumes:
            - "./:/var/www/html/"
        ports:
            - 81:80
            - 444:443
        networks:
            - backend

    mysql:
        image: mysql
        user: mysql
        environment:
            MYSQL_ROOT_PASSWORD: sfbp
            MYSQL_DATABASE: sfbp
            MYSQL_USER: sfbp
            MYSQL_PASSWORD: sfbp
        volumes:
            - "./docker/var/logs/mysql/:/var/log/mysql/"
            - "./docker/var/data/mysql/:/var/lib/mysql/"
        ports:
            - 3307:3306
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_USER: sfbp
            PMA_PASSWORD: sfbp
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - 82:80
        networks:
            - backend

    redis:
        image: redis
        ports:
            - 6380:6379
        networks:
            - backend

    memcached:
        image: memcached
        ports:
            - 11212:11211
        networks:
            - backend

# Networks
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
