services:
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments:
            - ~
            - CoreBundle\Entity\User
            - AdminBundle:User
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: Users
        calls:
            - [setContainer, ["@service_container"]]

    admin.user_action:
        class: AdminBundle\Admin\UserActionAdmin
        arguments:
            - ~
            - CoreBundle\Entity\UserAction
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Actions
        calls:
            - [setContainer, ["@service_container"]]

    admin.user_recovery_code:
        class: AdminBundle\Admin\UserRecoveryCodeAdmin
        arguments:
            - ~
            - CoreBundle\Entity\UserRecoveryCode
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Recovery Codes
        calls:
            - [setContainer, ["@service_container"]]

    admin.login_code:
        class: AdminBundle\Admin\UserLoginCodeAdmin
        arguments:
            - ~
            - CoreBundle\Entity\UserLoginCode
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Login Codes
        calls:
            - [setContainer, ["@service_container"]]

    admin.user_blocked_action:
        class: AdminBundle\Admin\UserBlockedActionAdmin
        arguments:
            - ~
            - CoreBundle\Entity\UserBlockedAction
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Blocked Actions
        calls:
            - [setContainer, ["@service_container"]]

    admin.user_device:
        class: AdminBundle\Admin\UserDeviceAdmin
        arguments:
            - ~
            - CoreBundle\Entity\UserDevice
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Devices
        calls:
            - [setContainer, ["@service_container"]]
