sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: "Administration"
    title_logo: 'http://corcosoft.com/assets/images/logo/icon.png'

services:
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments:
            - ~
            - AppBundle\Entity\User
            - AdminBundle:User
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: Users
        calls:
            - [setContainer, ["@service_container"]]

    admin.user_action:
        class: AdminBundle\Admin\UserActionAdmin
        arguments:
            - ~
            - AppBundle\Entity\UserAction
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Actions
        calls:
            - [setContainer, ["@service_container"]]

    admin.user_backup_code:
        class: AdminBundle\Admin\UserBackupCodeAdmin
        arguments:
            - ~
            - AppBundle\Entity\UserBackupCode
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Backup Codes
        calls:
            - [setContainer, ["@service_container"]]

    admin.user_trusted_device:
        class: AdminBundle\Admin\UserTrustedDeviceAdmin
        arguments:
            - ~
            - AppBundle\Entity\UserTrustedDevice
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Trusted Devices
        calls:
            - [setContainer, ["@service_container"]]

    admin.login_code:
        class: AdminBundle\Admin\UserLoginCodeAdmin
        arguments:
            - ~
            - AppBundle\Entity\UserLoginCode
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: General
              label: User Login Codes
        calls:
            - [setContainer, ["@service_container"]]
