imports:
    - { resource: config.yml }

swiftmailer:
    spool:
        type: file
        path: '%kernel.cache_dir%/swiftmailer/spool'

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_404s:
                - ^/phpmyadmin
        grouped:
            type: group
            members: [streamed, deduplicated]
        streamed:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        deduplicated:
            type: deduplication
            handler: swift
        swift:
            type: swift_mailer
            from_email: 'errors@corcosoft.com'
            to_email: 'errors@corcosoft.com'
            subject: '[App] An Error Occurred (%%message%%)'
            level:  debug
            formatter:  monolog.formatter.html
            content_type: text/html
        console:
            type:  console
