imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    # General
    locale: en_US
    locales:
        - en_US
        - de_DE
    app_name: SymfonyBoilerplate
    description: My personal symfony boilerplate.
    author: Borut Balazek
    # Email sender
    sender_address: sfbp@corcosoft.com # from which email will the emails be sent
    sender_name: Symfony Boilerplate Mailer # name of the sender, from which the emails will be sent
    # Versions
    version: "v0.1.0-dev"
    assets_version: "v2017-03-28-00-00"
    # Date & time formats
    date_format: "d.m.Y"
    date_time_format: "d.m.Y H:i:s"
    # Upload
    uploads_directory: "%kernel.root_dir%/../web/assets/uploads"
    uploads_path: "/assets/uploads"
    # Deployment
    deployment_emails: # to whom should the email be sent, after a successful deployment?
        bobalazek124@gmail.com: "Borut Balazek"
    # Brute force
    brute_force_max_attempts: 10
    brute_force_block_time: 600 # in seconds; 10 minutes
    brute_force_watch_time: 300 # in seconds; 5 minutes; compare the last X (watch_time) seconds if Y (max_attempts_before_block) attempts appeared
    # Reset password
    reset_password_expiry_time: 900 # in seconds; 15 minutes
    # Recovery codes
    recovery_codes_count: 8 # how many codes should be generated?
    # Login code
    login_code_expiry_time: 600 # in seconds; 10 minutes; for how long is the login code valid?
    # Other
    knp.doctrine_behaviors.blameable_subscriber.user_entity: CoreBundle\Entity\User
    app.security.authentication.listener.form.class: CoreBundle\EventListener\UsernamePasswordFormAuthenticationListener

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer:
        enabled: true
        enable_annotations: true
    templating:
        engines: [ "twig" ]
    default_locale: "%locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.pdo
    fragments:  ~
    http_method_override: true
    assets:
        version: "%assets_version%"
    php_errors:
        log: true
    translator:
        fallbacks: [ "%locale%" ]
        paths:
            - "%kernel.root_dir%/../src"

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        globals: # we want to access those variables literally via "globals.{variable}"
            locale: "%locale%"
            app_name: "%app_name%"
            description: "%description%"
            author: "%author%"
            version: "%version%"
            copyright: "Copyright © %author% 2017. All rights reserved."
            assets_version: "%assets_version%"
            date_format: "%date_format%"
            date_time_format: "%date_time_format%"
    form_themes:
        - CoreBundle:Form:layout.html.twig

# Assetic
assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            softdeleteabletrash:
                class: Picoss\SonataExtraAdminBundle\Filter\SoftDeleteableTrashFilter
                enabled: true

# Doctrine migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/CoreBundle/Migrations"
    namespace: CoreBundle\Migrations
    table_name: migration_versions
    name: Application Migrations

# Doctrine cache
doctrine_cache:
    providers:
        rate_limit_cache:
            type: file_system
            namespace: rate_limit
            file_system:
                directory: "%kernel.cache_dir%/doctrine/rate_limit"

# Doctrine behaviors
knp_doctrine_behaviors:
    blameable: true
    loggable: true
    timestampable: true
    soft_deletable: true

# Doctrine extensions
stof_doctrine_extensions:
    orm:
        default:
            loggable: true
            softdeleteable: true

# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    port: "%mailer_port%"
    encryption: "%mailer_encryption%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool: { type: memory }

# Paginator
knp_paginator:
    page_range: 5
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: CoreBundle:Pagination:sortable_link.html.twig
        filtration: CoreBundle:Pagination:filtration.html.twig

# CORS
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ["*"]
        allow_headers: ["*"]
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        max_age: 3600
        hosts: []
        origin_regex: false

# Serializer
jms_serializer:
    enable_short_alias: false

# Translations
jms_translation:
    locales: "%locales%"
    source_language: "%locale%"
    configs:
        CoreBundle:
            dirs:
                - "%kernel.root_dir%/../src/CoreBundle"
            output_dir: "%kernel.root_dir%/../src/CoreBundle/Resources/translations"
            default_output_format: xliff
        ApiBundle:
            dirs:
                - "%kernel.root_dir%/../src/ApiBundle"
            output_dir: "%kernel.root_dir%/../src/ApiBundle/Resources/translations"
            default_output_format: xliff
        AdminBundle:
            dirs:
                - "%kernel.root_dir%/../src/AdminBundle"
            output_dir: "%kernel.root_dir%/../src/AdminBundle/Resources/translations"
            default_output_format: xliff
        DevBundle:
            dirs:
                - "%kernel.root_dir%/../src/DevBundle"
            output_dir: "%kernel.root_dir%/../src/DevBundle/Resources/translations"
            default_output_format: xliff
        TfaBundle:
            dirs:
                - "%kernel.root_dir%/../src/TfaBundle"
            output_dir: "%kernel.root_dir%/../src/TfaBundle/Resources/translations"
            default_output_format: xliff

# Rate limiting
noxlogic_rate_limit:
    enabled: true
    storage_engine: doctrine
    doctrine_provider: rate_limit_cache
    rate_response_exception: CoreBundle\Exception\TooManyRequestsHttpException

# Sonata admin
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: "Administration"
    title_logo: "assets/img/logo/icon.png"
    templates:
        layout: "AdminBundle:Layout:default.html.twig"
        user_block: "AdminBundle:Layout:_user_block.html.twig"

    dashboard:
        blocks:
            - position: left
              type: sonata.admin.block.admin_list
              settings:
                  groups:
                      - users
                      - user_actions
                      - user_devices
            - position: right
              type: sonata.admin.block.admin_list
              settings:
                  groups:
                      - user_recovery_codes
                      - user_login_codes
                      - user_blocked_actions

        groups:
            users:
                on_top: true
                label: Users
                icon: '<i class="fa fa-users"></i>'
                items:
                    - admin.users

            user_actions:
                on_top: true
                label: User Actions
                icon: '<i class="fa fa-star"></i>'
                items:
                    - admin.user_actions

            user_devices:
                on_top: true
                label: User Devices
                icon: '<i class="fa fa-desktop"></i>'
                items:
                    - admin.user_devices

            user_recovery_codes:
                on_top: true
                label: User Recovery Codes
                icon: '<i class="fa fa-medkit"></i>'
                items:
                    - admin.user_recovery_codes

            user_login_codes:
                on_top: true
                label: User Login Codes
                icon: '<i class="fa fa-file-text"></i>'
                items:
                    - admin.user_login_codes

            user_blocked_actions:
                on_top: true
                label: User Blocked Actions
                icon: '<i class="fa fa-ban"></i>'
                items:
                    - admin.user_blocked_actions
