app:
    resource: "@AppBundle/Controller/"
    type: annotation

api:
    resource: "@ApiBundle/Controller/"
    type: annotation

admin:
    resource: "@AdminBundle/Controller/"
    type: annotation

logout:
    path: /logout
