app:
    resource: "@AppBundle/Controller/"
    type: annotation

api:
    resource: "@ApiBundle/Controller/"
    type: annotation

logout:
    path: /logout

admin:
    resource: "@AdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin