security:
    providers:
        user_provider:
            id: app.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            anonymous: ~
            stateless: true
            guard:
                authenticators:
                    - api.token_authenticator

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: login
                handlers: [ app.logout_listener ]
            switch_user: true
            remember_me:
                secret: "%secret%"

    access_control:
        - { path: ^/my, roles: ROLE_USER }
        - { path: ^/welcome, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        CoreBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]
