services:
    # Services
    app.emogrifier:
        class: AppBundle\Service\EmogrifierService
        calls:
            - [setContainer, ["@service_container"]]

    app.mailer:
        class: AppBundle\Service\MailerService
        calls:
            - [setContainer, ["@service_container"]]

    app.apifier:
        class: AppBundle\Service\ApifierService
        arguments: ["@request_stack"]
        calls:
            - [setContainer, ["@service_container"]]

    # Managers
    app.user_action_manager:
        class: AppBundle\Manager\UserActionManager
        calls:
            - [setContainer, ["@service_container"]]

    app.user_login_code_manager:
        class: AppBundle\Manager\UserLoginCodeManager
        calls:
            - [setContainer, ["@service_container"]]

    app.user_manager:
        class: AppBundle\Manager\UserManager
        calls:
            - [setContainer, ["@service_container"]]

    app.user_trusted_device_manager:
        class: AppBundle\Manager\UserTrustedDeviceManager
        calls:
            - [setContainer, ["@service_container"]]
            - [prepareVariables, []]

    app.two_factor_authentication_manager:
        class: AppBundle\Manager\TwoFactorAuthenticationManager
        calls:
            - [setContainer, ["@service_container"]]

    app.brute_force_manager:
        class: AppBundle\Manager\BruteForceManager
        calls:
            - [setContainer, ["@service_container"]]

    # Security
    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]

    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator

    # Twig
    app.twig_core_extension:
        class: AppBundle\Twig\CoreExtension
        public: false
        tags:
            - { name: twig.extension }
        calls:
            - [setContainer, ["@service_container"]]

    # Event Subscribers & Listeners
    app.authentication_subscriber:
        class: AppBundle\EventSubscriber\AuthenticationSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.user_action_manager"
            - "@app.brute_force_manager"

    app.security_subscriber:
        class: AppBundle\EventSubscriber\SecuritySubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@app.user_action_manager"
            - "@app.two_factor_authentication_manager"

    app.logout_listener:
        class: AppBundle\EventListener\LogoutListener
        arguments: [ "@app.user_action_manager" ]

    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.general_listener:
        class: AppBundle\EventListener\GeneralListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    # Form types
    app.form.type.user:
        class: AppBundle\Form\Type\UserType
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: form.type }

    # Session
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public: false
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%' }
