imports:
    - { resource: services_aliases.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # General
    CoreBundle\Service\EmogrifierService: ~

    CoreBundle\Service\MailerService: ~

    CoreBundle\Service\SmsSenderService: ~

    CoreBundle\Service\ApifierService: ~

    # Managers
    CoreBundle\Manager\UserManager: ~

    CoreBundle\Manager\UserActionManager: ~

    CoreBundle\Manager\UserDeviceManager: ~

    CoreBundle\Manager\UserLoginCodeManager: ~

    CoreBundle\Manager\UserRecoveryCodeManager: ~

    CoreBundle\Manager\BruteForceManager: ~

    Google\Authenticator\GoogleAuthenticator: ~

    # Security
    CoreBundle\Security\UserProvider: ~

    # Twig
    CoreBundle\Twig\CoreExtension:
        tags:
            - name: twig.extension
        calls:
            - [setContainer, ["@service_container"]]

    Twig_Extensions_Extension_Text:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    # Event Subscribers & Listeners
    CoreBundle\EventSubscriber\AuthenticationSubscriber: ~

    CoreBundle\EventSubscriber\SecuritySubscriber: ~

    CoreBundle\EventListener\LogoutListener: ~

    CoreBundle\EventListener\ExceptionListener:
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    CoreBundle\EventListener\GeneralListener:
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }
            - { name: kernel.event_listener, event: kernel.response }

    # Form types
    CoreBundle\Form\Type\UserType:
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: form.type }

    # Session
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - "mysql:host=%database_host%;dbname=%database_name%"
            - { db_username: "%database_user%", db_password: "%database_password%" }

    Memcached:
        class: 'Memcached'
        calls:
            - [addServer, ["%memcached_host%", "%memcached_port%"]]

    Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler:
        arguments:
            - "@session.memcached"
            - { prefix: "%memcached_prefix%", expiretime: "%memcached_expire%" }
