local_server:
    local: true
    roles: app
    stage: dev
    deploy_path: ~/Development/Deployment/symfony-boilerplate

production_server:
  host: 128.128.128.128
  port: 22
  user: root
  forward_agent: ~
  stage: prod
  roles: app
  deploy_path: /var/www/html/deployment/production
  branch: master
