local_server:
    local: true
    stage: dev
    env: dev
    branch: master
    deploy_path: ~/Development/Deployment/symfony-boilerplate

production_server:
    host: 128.128.128.128
    port: 22
    user: root
    forward_agent: ~
    stage: prod
    env: prod
    branch: master
    deploy_path: /var/www/html/deployment/production
